version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  postgres:
    image: library/postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: 'dengi'
    ports:
      - 5432:5432
  pgadmin:
    image: fenglc/pgadmin4
    environment:
      DEFAULT_USER: 'pgadmin4@pgadmin.org'
      DEFAULT_PASSWORD: 'admin'
    ports:
      - 5050:5050